// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package collector

import (
	"context"
	"time"

	"github.com/go-ble/ble"
	mock "github.com/stretchr/testify/mock"
)

// NewMockBLEDevice creates a new instance of MockBLEDevice. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBLEDevice(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBLEDevice {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockBLEDevice{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockBLEDevice is an autogenerated mock type for the BLEDevice type
type MockBLEDevice struct {
	mock.Mock
}

type MockBLEDevice_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBLEDevice) EXPECT() *MockBLEDevice_Expecter {
	return &MockBLEDevice_Expecter{mock: &_m.Mock}
}

// Dial provides a mock function for the type MockBLEDevice
func (_mock *MockBLEDevice) Dial(context1 context.Context, addr ble.Addr) (ble.Client, error) {
	ret := _mock.Called(context1, addr)

	if len(ret) == 0 {
		panic("no return value specified for Dial")
	}

	var r0 ble.Client
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ble.Addr) (ble.Client, error)); ok {
		return returnFunc(context1, addr)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ble.Addr) ble.Client); ok {
		r0 = returnFunc(context1, addr)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(ble.Client)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ble.Addr) error); ok {
		r1 = returnFunc(context1, addr)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBLEDevice_Dial_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Dial'
type MockBLEDevice_Dial_Call struct {
	*mock.Call
}

// Dial is a helper method to define mock.On call
//   - context1 context.Context
//   - addr ble.Addr
func (_e *MockBLEDevice_Expecter) Dial(context1 any, addr any) *MockBLEDevice_Dial_Call {
	return &MockBLEDevice_Dial_Call{Call: _e.mock.On("Dial", context1, addr)}
}

func (_c *MockBLEDevice_Dial_Call) Run(run func(context1 context.Context, addr ble.Addr)) *MockBLEDevice_Dial_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ble.Addr
		if args[1] != nil {
			arg1 = args[1].(ble.Addr)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBLEDevice_Dial_Call) Return(client ble.Client, err error) *MockBLEDevice_Dial_Call {
	_c.Call.Return(client, err)
	return _c
}

func (_c *MockBLEDevice_Dial_Call) RunAndReturn(run func(context1 context.Context, addr ble.Addr) (ble.Client, error)) *MockBLEDevice_Dial_Call {
	_c.Call.Return(run)
	return _c
}

// Scan provides a mock function for the type MockBLEDevice
func (_mock *MockBLEDevice) Scan(ctx context.Context, allowDuplicates bool, handler ble.AdvHandler) error {
	ret := _mock.Called(ctx, allowDuplicates, handler)

	if len(ret) == 0 {
		panic("no return value specified for Scan")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, bool, ble.AdvHandler) error); ok {
		r0 = returnFunc(ctx, allowDuplicates, handler)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBLEDevice_Scan_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Scan'
type MockBLEDevice_Scan_Call struct {
	*mock.Call
}

// Scan is a helper method to define mock.On call
//   - ctx context.Context
//   - allowDuplicates bool
//   - handler ble.AdvHandler
func (_e *MockBLEDevice_Expecter) Scan(ctx any, allowDuplicates any, handler any) *MockBLEDevice_Scan_Call {
	return &MockBLEDevice_Scan_Call{Call: _e.mock.On("Scan", ctx, allowDuplicates, handler)}
}

func (_c *MockBLEDevice_Scan_Call) Run(run func(ctx context.Context, allowDuplicates bool, handler ble.AdvHandler)) *MockBLEDevice_Scan_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 bool
		if args[1] != nil {
			arg1 = args[1].(bool)
		}
		var arg2 ble.AdvHandler
		if args[2] != nil {
			arg2 = args[2].(ble.AdvHandler)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockBLEDevice_Scan_Call) Return(err error) *MockBLEDevice_Scan_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBLEDevice_Scan_Call) RunAndReturn(run func(ctx context.Context, allowDuplicates bool, handler ble.AdvHandler) error) *MockBLEDevice_Scan_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockBLEScanner creates a new instance of MockBLEScanner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBLEScanner(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBLEScanner {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockBLEScanner{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockBLEScanner is an autogenerated mock type for the BLEScanner type
type MockBLEScanner struct {
	mock.Mock
}

type MockBLEScanner_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBLEScanner) EXPECT() *MockBLEScanner_Expecter {
	return &MockBLEScanner_Expecter{mock: &_m.Mock}
}

// ScanLoop provides a mock function for the type MockBLEScanner
func (_mock *MockBLEScanner) ScanLoop(ctx context.Context, filter ble.AdvFilter) (<-chan TimedAdvertisement, <-chan error, error) {
	ret := _mock.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for ScanLoop")
	}

	var r0 <-chan TimedAdvertisement
	var r1 <-chan error
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ble.AdvFilter) (<-chan TimedAdvertisement, <-chan error, error)); ok {
		return returnFunc(ctx, filter)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ble.AdvFilter) <-chan TimedAdvertisement); ok {
		r0 = returnFunc(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan TimedAdvertisement)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ble.AdvFilter) <-chan error); ok {
		r1 = returnFunc(ctx, filter)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(<-chan error)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, ble.AdvFilter) error); ok {
		r2 = returnFunc(ctx, filter)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockBLEScanner_ScanLoop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ScanLoop'
type MockBLEScanner_ScanLoop_Call struct {
	*mock.Call
}

// ScanLoop is a helper method to define mock.On call
//   - ctx context.Context
//   - filter ble.AdvFilter
func (_e *MockBLEScanner_Expecter) ScanLoop(ctx any, filter any) *MockBLEScanner_ScanLoop_Call {
	return &MockBLEScanner_ScanLoop_Call{Call: _e.mock.On("ScanLoop", ctx, filter)}
}

func (_c *MockBLEScanner_ScanLoop_Call) Run(run func(ctx context.Context, filter ble.AdvFilter)) *MockBLEScanner_ScanLoop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ble.AdvFilter
		if args[1] != nil {
			arg1 = args[1].(ble.AdvFilter)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBLEScanner_ScanLoop_Call) Return(timedAdvertisementCh <-chan TimedAdvertisement, errCh <-chan error, err error) *MockBLEScanner_ScanLoop_Call {
	_c.Call.Return(timedAdvertisementCh, errCh, err)
	return _c
}

func (_c *MockBLEScanner_ScanLoop_Call) RunAndReturn(run func(ctx context.Context, filter ble.AdvFilter) (<-chan TimedAdvertisement, <-chan error, error)) *MockBLEScanner_ScanLoop_Call {
	_c.Call.Return(run)
	return _c
}

// Schedule provides a mock function for the type MockBLEScanner
func (_mock *MockBLEScanner) Schedule(task BLETask) error {
	ret := _mock.Called(task)

	if len(ret) == 0 {
		panic("no return value specified for Schedule")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(BLETask) error); ok {
		r0 = returnFunc(task)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBLEScanner_Schedule_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Schedule'
type MockBLEScanner_Schedule_Call struct {
	*mock.Call
}

// Schedule is a helper method to define mock.On call
//   - task BLETask
func (_e *MockBLEScanner_Expecter) Schedule(task any) *MockBLEScanner_Schedule_Call {
	return &MockBLEScanner_Schedule_Call{Call: _e.mock.On("Schedule", task)}
}

func (_c *MockBLEScanner_Schedule_Call) Run(run func(task BLETask)) *MockBLEScanner_Schedule_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 BLETask
		if args[0] != nil {
			arg0 = args[0].(BLETask)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockBLEScanner_Schedule_Call) Return(err error) *MockBLEScanner_Schedule_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBLEScanner_Schedule_Call) RunAndReturn(run func(task BLETask) error) *MockBLEScanner_Schedule_Call {
	_c.Call.Return(run)
	return _c
}

// newMockenvironmentalOperator creates a new instance of mockenvironmentalOperator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockenvironmentalOperator(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockenvironmentalOperator {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &mockenvironmentalOperator{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// mockenvironmentalOperator is an autogenerated mock type for the environmentalOperator type
type mockenvironmentalOperator struct {
	mock.Mock
}

type mockenvironmentalOperator_Expecter struct {
	mock *mock.Mock
}

func (_m *mockenvironmentalOperator) EXPECT() *mockenvironmentalOperator_Expecter {
	return &mockenvironmentalOperator_Expecter{mock: &_m.Mock}
}

// ReadJournalAndEraseDevice provides a mock function for the type mockenvironmentalOperator
func (_mock *mockenvironmentalOperator) ReadJournalAndEraseDevice(ctx context.Context, dev BLEDevice, address ble.Addr, locationID string, journal DataJournal) error {
	ret := _mock.Called(ctx, dev, address, locationID, journal)

	if len(ret) == 0 {
		panic("no return value specified for ReadJournalAndEraseDevice")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, BLEDevice, ble.Addr, string, DataJournal) error); ok {
		r0 = returnFunc(ctx, dev, address, locationID, journal)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockenvironmentalOperator_ReadJournalAndEraseDevice_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadJournalAndEraseDevice'
type mockenvironmentalOperator_ReadJournalAndEraseDevice_Call struct {
	*mock.Call
}

// ReadJournalAndEraseDevice is a helper method to define mock.On call
//   - ctx context.Context
//   - dev BLEDevice
//   - address ble.Addr
//   - locationID string
//   - journal DataJournal
func (_e *mockenvironmentalOperator_Expecter) ReadJournalAndEraseDevice(ctx any, dev any, address any, locationID any, journal any) *mockenvironmentalOperator_ReadJournalAndEraseDevice_Call {
	return &mockenvironmentalOperator_ReadJournalAndEraseDevice_Call{Call: _e.mock.On("ReadJournalAndEraseDevice", ctx, dev, address, locationID, journal)}
}

func (_c *mockenvironmentalOperator_ReadJournalAndEraseDevice_Call) Run(run func(ctx context.Context, dev BLEDevice, address ble.Addr, locationID string, journal DataJournal)) *mockenvironmentalOperator_ReadJournalAndEraseDevice_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 BLEDevice
		if args[1] != nil {
			arg1 = args[1].(BLEDevice)
		}
		var arg2 ble.Addr
		if args[2] != nil {
			arg2 = args[2].(ble.Addr)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 DataJournal
		if args[4] != nil {
			arg4 = args[4].(DataJournal)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *mockenvironmentalOperator_ReadJournalAndEraseDevice_Call) Return(err error) *mockenvironmentalOperator_ReadJournalAndEraseDevice_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockenvironmentalOperator_ReadJournalAndEraseDevice_Call) RunAndReturn(run func(ctx context.Context, dev BLEDevice, address ble.Addr, locationID string, journal DataJournal) error) *mockenvironmentalOperator_ReadJournalAndEraseDevice_Call {
	_c.Call.Return(run)
	return _c
}

// SynchronizeDevice provides a mock function for the type mockenvironmentalOperator
func (_mock *mockenvironmentalOperator) SynchronizeDevice(ctx context.Context, dev BLEDevice, address ble.Addr) error {
	ret := _mock.Called(ctx, dev, address)

	if len(ret) == 0 {
		panic("no return value specified for SynchronizeDevice")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, BLEDevice, ble.Addr) error); ok {
		r0 = returnFunc(ctx, dev, address)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockenvironmentalOperator_SynchronizeDevice_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SynchronizeDevice'
type mockenvironmentalOperator_SynchronizeDevice_Call struct {
	*mock.Call
}

// SynchronizeDevice is a helper method to define mock.On call
//   - ctx context.Context
//   - dev BLEDevice
//   - address ble.Addr
func (_e *mockenvironmentalOperator_Expecter) SynchronizeDevice(ctx any, dev any, address any) *mockenvironmentalOperator_SynchronizeDevice_Call {
	return &mockenvironmentalOperator_SynchronizeDevice_Call{Call: _e.mock.On("SynchronizeDevice", ctx, dev, address)}
}

func (_c *mockenvironmentalOperator_SynchronizeDevice_Call) Run(run func(ctx context.Context, dev BLEDevice, address ble.Addr)) *mockenvironmentalOperator_SynchronizeDevice_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 BLEDevice
		if args[1] != nil {
			arg1 = args[1].(BLEDevice)
		}
		var arg2 ble.Addr
		if args[2] != nil {
			arg2 = args[2].(ble.Addr)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockenvironmentalOperator_SynchronizeDevice_Call) Return(err error) *mockenvironmentalOperator_SynchronizeDevice_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockenvironmentalOperator_SynchronizeDevice_Call) RunAndReturn(run func(ctx context.Context, dev BLEDevice, address ble.Addr) error) *mockenvironmentalOperator_SynchronizeDevice_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockClock creates a new instance of MockClock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClock(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClock {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockClock{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockClock is an autogenerated mock type for the Clock type
type MockClock struct {
	mock.Mock
}

type MockClock_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClock) EXPECT() *MockClock_Expecter {
	return &MockClock_Expecter{mock: &_m.Mock}
}

// NewTimer provides a mock function for the type MockClock
func (_mock *MockClock) NewTimer(d time.Duration) *time.Timer {
	ret := _mock.Called(d)

	if len(ret) == 0 {
		panic("no return value specified for NewTimer")
	}

	var r0 *time.Timer
	if returnFunc, ok := ret.Get(0).(func(time.Duration) *time.Timer); ok {
		r0 = returnFunc(d)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*time.Timer)
		}
	}
	return r0
}

// MockClock_NewTimer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewTimer'
type MockClock_NewTimer_Call struct {
	*mock.Call
}

// NewTimer is a helper method to define mock.On call
//   - d time.Duration
func (_e *MockClock_Expecter) NewTimer(d any) *MockClock_NewTimer_Call {
	return &MockClock_NewTimer_Call{Call: _e.mock.On("NewTimer", d)}
}

func (_c *MockClock_NewTimer_Call) Run(run func(d time.Duration)) *MockClock_NewTimer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 time.Duration
		if args[0] != nil {
			arg0 = args[0].(time.Duration)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockClock_NewTimer_Call) Return(timer *time.Timer) *MockClock_NewTimer_Call {
	_c.Call.Return(timer)
	return _c
}

func (_c *MockClock_NewTimer_Call) RunAndReturn(run func(d time.Duration) *time.Timer) *MockClock_NewTimer_Call {
	_c.Call.Return(run)
	return _c
}

// Now provides a mock function for the type MockClock
func (_mock *MockClock) Now() time.Time {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Now")
	}

	var r0 time.Time
	if returnFunc, ok := ret.Get(0).(func() time.Time); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(time.Time)
	}
	return r0
}

// MockClock_Now_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Now'
type MockClock_Now_Call struct {
	*mock.Call
}

// Now is a helper method to define mock.On call
func (_e *MockClock_Expecter) Now() *MockClock_Now_Call {
	return &MockClock_Now_Call{Call: _e.mock.On("Now")}
}

func (_c *MockClock_Now_Call) Run(run func()) *MockClock_Now_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClock_Now_Call) Return(time1 time.Time) *MockClock_Now_Call {
	_c.Call.Return(time1)
	return _c
}

func (_c *MockClock_Now_Call) RunAndReturn(run func() time.Time) *MockClock_Now_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCronScheduler creates a new instance of MockCronScheduler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCronScheduler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCronScheduler {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockCronScheduler{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockCronScheduler is an autogenerated mock type for the CronScheduler type
type MockCronScheduler struct {
	mock.Mock
}

type MockCronScheduler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCronScheduler) EXPECT() *MockCronScheduler_Expecter {
	return &MockCronScheduler_Expecter{mock: &_m.Mock}
}

// ScheduleLoop provides a mock function for the type MockCronScheduler
func (_mock *MockCronScheduler) ScheduleLoop(ctx context.Context, hod HourOfDay, fn func(time.Time)) {
	_mock.Called(ctx, hod, fn)
	return
}

// MockCronScheduler_ScheduleLoop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ScheduleLoop'
type MockCronScheduler_ScheduleLoop_Call struct {
	*mock.Call
}

// ScheduleLoop is a helper method to define mock.On call
//   - ctx context.Context
//   - hod HourOfDay
//   - fn func(time.Time)
func (_e *MockCronScheduler_Expecter) ScheduleLoop(ctx any, hod any, fn any) *MockCronScheduler_ScheduleLoop_Call {
	return &MockCronScheduler_ScheduleLoop_Call{Call: _e.mock.On("ScheduleLoop", ctx, hod, fn)}
}

func (_c *MockCronScheduler_ScheduleLoop_Call) Run(run func(ctx context.Context, hod HourOfDay, fn func(time.Time))) *MockCronScheduler_ScheduleLoop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 HourOfDay
		if args[1] != nil {
			arg1 = args[1].(HourOfDay)
		}
		var arg2 func(time.Time)
		if args[2] != nil {
			arg2 = args[2].(func(time.Time))
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockCronScheduler_ScheduleLoop_Call) Return() *MockCronScheduler_ScheduleLoop_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockCronScheduler_ScheduleLoop_Call) RunAndReturn(run func(ctx context.Context, hod HourOfDay, fn func(time.Time))) *MockCronScheduler_ScheduleLoop_Call {
	_c.Run(run)
	return _c
}

// NewMockDataJournal creates a new instance of MockDataJournal. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDataJournal(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDataJournal {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockDataJournal{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockDataJournal is an autogenerated mock type for the DataJournal type
type MockDataJournal struct {
	mock.Mock
}

type MockDataJournal_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDataJournal) EXPECT() *MockDataJournal_Expecter {
	return &MockDataJournal_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type MockDataJournal
func (_mock *MockDataJournal) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDataJournal_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockDataJournal_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockDataJournal_Expecter) Close() *MockDataJournal_Close_Call {
	return &MockDataJournal_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockDataJournal_Close_Call) Run(run func()) *MockDataJournal_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDataJournal_Close_Call) Return(err error) *MockDataJournal_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDataJournal_Close_Call) RunAndReturn(run func() error) *MockDataJournal_Close_Call {
	_c.Call.Return(run)
	return _c
}

// GetActiveAssignments provides a mock function for the type MockDataJournal
func (_mock *MockDataJournal) GetActiveAssignments(ctx context.Context) ([]SensorAssignement, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetActiveAssignments")
	}

	var r0 []SensorAssignement
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]SensorAssignement, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []SensorAssignement); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]SensorAssignement)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDataJournal_GetActiveAssignments_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetActiveAssignments'
type MockDataJournal_GetActiveAssignments_Call struct {
	*mock.Call
}

// GetActiveAssignments is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockDataJournal_Expecter) GetActiveAssignments(ctx any) *MockDataJournal_GetActiveAssignments_Call {
	return &MockDataJournal_GetActiveAssignments_Call{Call: _e.mock.On("GetActiveAssignments", ctx)}
}

func (_c *MockDataJournal_GetActiveAssignments_Call) Run(run func(ctx context.Context)) *MockDataJournal_GetActiveAssignments_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDataJournal_GetActiveAssignments_Call) Return(sensorAssignements []SensorAssignement, err error) *MockDataJournal_GetActiveAssignments_Call {
	_c.Call.Return(sensorAssignements, err)
	return _c
}

func (_c *MockDataJournal_GetActiveAssignments_Call) RunAndReturn(run func(ctx context.Context) ([]SensorAssignement, error)) *MockDataJournal_GetActiveAssignments_Call {
	_c.Call.Return(run)
	return _c
}

// GetEnvironmentalHistory provides a mock function for the type MockDataJournal
func (_mock *MockDataJournal) GetEnvironmentalHistory(ctx context.Context, locationID string, start time.Time, end time.Time) ([]EnvironmentalReading, error) {
	ret := _mock.Called(ctx, locationID, start, end)

	if len(ret) == 0 {
		panic("no return value specified for GetEnvironmentalHistory")
	}

	var r0 []EnvironmentalReading
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Time, time.Time) ([]EnvironmentalReading, error)); ok {
		return returnFunc(ctx, locationID, start, end)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Time, time.Time) []EnvironmentalReading); ok {
		r0 = returnFunc(ctx, locationID, start, end)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]EnvironmentalReading)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, time.Time, time.Time) error); ok {
		r1 = returnFunc(ctx, locationID, start, end)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDataJournal_GetEnvironmentalHistory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEnvironmentalHistory'
type MockDataJournal_GetEnvironmentalHistory_Call struct {
	*mock.Call
}

// GetEnvironmentalHistory is a helper method to define mock.On call
//   - ctx context.Context
//   - locationID string
//   - start time.Time
//   - end time.Time
func (_e *MockDataJournal_Expecter) GetEnvironmentalHistory(ctx any, locationID any, start any, end any) *MockDataJournal_GetEnvironmentalHistory_Call {
	return &MockDataJournal_GetEnvironmentalHistory_Call{Call: _e.mock.On("GetEnvironmentalHistory", ctx, locationID, start, end)}
}

func (_c *MockDataJournal_GetEnvironmentalHistory_Call) Run(run func(ctx context.Context, locationID string, start time.Time, end time.Time)) *MockDataJournal_GetEnvironmentalHistory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		var arg3 time.Time
		if args[3] != nil {
			arg3 = args[3].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockDataJournal_GetEnvironmentalHistory_Call) Return(environmentalReadings []EnvironmentalReading, err error) *MockDataJournal_GetEnvironmentalHistory_Call {
	_c.Call.Return(environmentalReadings, err)
	return _c
}

func (_c *MockDataJournal_GetEnvironmentalHistory_Call) RunAndReturn(run func(ctx context.Context, locationID string, start time.Time, end time.Time) ([]EnvironmentalReading, error)) *MockDataJournal_GetEnvironmentalHistory_Call {
	_c.Call.Return(run)
	return _c
}

// GetLocationAssignements provides a mock function for the type MockDataJournal
func (_mock *MockDataJournal) GetLocationAssignements(ctx context.Context, locationID string) ([]SensorAssignement, error) {
	ret := _mock.Called(ctx, locationID)

	if len(ret) == 0 {
		panic("no return value specified for GetLocationAssignements")
	}

	var r0 []SensorAssignement
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]SensorAssignement, error)); ok {
		return returnFunc(ctx, locationID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []SensorAssignement); ok {
		r0 = returnFunc(ctx, locationID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]SensorAssignement)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, locationID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDataJournal_GetLocationAssignements_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLocationAssignements'
type MockDataJournal_GetLocationAssignements_Call struct {
	*mock.Call
}

// GetLocationAssignements is a helper method to define mock.On call
//   - ctx context.Context
//   - locationID string
func (_e *MockDataJournal_Expecter) GetLocationAssignements(ctx any, locationID any) *MockDataJournal_GetLocationAssignements_Call {
	return &MockDataJournal_GetLocationAssignements_Call{Call: _e.mock.On("GetLocationAssignements", ctx, locationID)}
}

func (_c *MockDataJournal_GetLocationAssignements_Call) Run(run func(ctx context.Context, locationID string)) *MockDataJournal_GetLocationAssignements_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDataJournal_GetLocationAssignements_Call) Return(sensorAssignements []SensorAssignement, err error) *MockDataJournal_GetLocationAssignements_Call {
	_c.Call.Return(sensorAssignements, err)
	return _c
}

func (_c *MockDataJournal_GetLocationAssignements_Call) RunAndReturn(run func(ctx context.Context, locationID string) ([]SensorAssignement, error)) *MockDataJournal_GetLocationAssignements_Call {
	_c.Call.Return(run)
	return _c
}

// GetSensorAssignements provides a mock function for the type MockDataJournal
func (_mock *MockDataJournal) GetSensorAssignements(ctx context.Context, sensorID string) ([]SensorAssignement, error) {
	ret := _mock.Called(ctx, sensorID)

	if len(ret) == 0 {
		panic("no return value specified for GetSensorAssignements")
	}

	var r0 []SensorAssignement
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]SensorAssignement, error)); ok {
		return returnFunc(ctx, sensorID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []SensorAssignement); ok {
		r0 = returnFunc(ctx, sensorID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]SensorAssignement)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, sensorID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDataJournal_GetSensorAssignements_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSensorAssignements'
type MockDataJournal_GetSensorAssignements_Call struct {
	*mock.Call
}

// GetSensorAssignements is a helper method to define mock.On call
//   - ctx context.Context
//   - sensorID string
func (_e *MockDataJournal_Expecter) GetSensorAssignements(ctx any, sensorID any) *MockDataJournal_GetSensorAssignements_Call {
	return &MockDataJournal_GetSensorAssignements_Call{Call: _e.mock.On("GetSensorAssignements", ctx, sensorID)}
}

func (_c *MockDataJournal_GetSensorAssignements_Call) Run(run func(ctx context.Context, sensorID string)) *MockDataJournal_GetSensorAssignements_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDataJournal_GetSensorAssignements_Call) Return(sensorAssignements []SensorAssignement, err error) *MockDataJournal_GetSensorAssignements_Call {
	_c.Call.Return(sensorAssignements, err)
	return _c
}

func (_c *MockDataJournal_GetSensorAssignements_Call) RunAndReturn(run func(ctx context.Context, sensorID string) ([]SensorAssignement, error)) *MockDataJournal_GetSensorAssignements_Call {
	_c.Call.Return(run)
	return _c
}

// GetSensorLocations provides a mock function for the type MockDataJournal
func (_mock *MockDataJournal) GetSensorLocations(ctx context.Context) ([]SensorLocation, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetSensorLocations")
	}

	var r0 []SensorLocation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]SensorLocation, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []SensorLocation); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]SensorLocation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDataJournal_GetSensorLocations_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSensorLocations'
type MockDataJournal_GetSensorLocations_Call struct {
	*mock.Call
}

// GetSensorLocations is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockDataJournal_Expecter) GetSensorLocations(ctx any) *MockDataJournal_GetSensorLocations_Call {
	return &MockDataJournal_GetSensorLocations_Call{Call: _e.mock.On("GetSensorLocations", ctx)}
}

func (_c *MockDataJournal_GetSensorLocations_Call) Run(run func(ctx context.Context)) *MockDataJournal_GetSensorLocations_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDataJournal_GetSensorLocations_Call) Return(sensorLocations []SensorLocation, err error) *MockDataJournal_GetSensorLocations_Call {
	_c.Call.Return(sensorLocations, err)
	return _c
}

func (_c *MockDataJournal_GetSensorLocations_Call) RunAndReturn(run func(ctx context.Context) ([]SensorLocation, error)) *MockDataJournal_GetSensorLocations_Call {
	_c.Call.Return(run)
	return _c
}

// SaveEnvironmentalReadings provides a mock function for the type MockDataJournal
func (_mock *MockDataJournal) SaveEnvironmentalReadings(ctx context.Context, readings []EnvironmentalReading) error {
	ret := _mock.Called(ctx, readings)

	if len(ret) == 0 {
		panic("no return value specified for SaveEnvironmentalReadings")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []EnvironmentalReading) error); ok {
		r0 = returnFunc(ctx, readings)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDataJournal_SaveEnvironmentalReadings_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveEnvironmentalReadings'
type MockDataJournal_SaveEnvironmentalReadings_Call struct {
	*mock.Call
}

// SaveEnvironmentalReadings is a helper method to define mock.On call
//   - ctx context.Context
//   - readings []EnvironmentalReading
func (_e *MockDataJournal_Expecter) SaveEnvironmentalReadings(ctx any, readings any) *MockDataJournal_SaveEnvironmentalReadings_Call {
	return &MockDataJournal_SaveEnvironmentalReadings_Call{Call: _e.mock.On("SaveEnvironmentalReadings", ctx, readings)}
}

func (_c *MockDataJournal_SaveEnvironmentalReadings_Call) Run(run func(ctx context.Context, readings []EnvironmentalReading)) *MockDataJournal_SaveEnvironmentalReadings_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []EnvironmentalReading
		if args[1] != nil {
			arg1 = args[1].([]EnvironmentalReading)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDataJournal_SaveEnvironmentalReadings_Call) Return(err error) *MockDataJournal_SaveEnvironmentalReadings_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDataJournal_SaveEnvironmentalReadings_Call) RunAndReturn(run func(ctx context.Context, readings []EnvironmentalReading) error) *MockDataJournal_SaveEnvironmentalReadings_Call {
	_c.Call.Return(run)
	return _c
}

// SaveLocation provides a mock function for the type MockDataJournal
func (_mock *MockDataJournal) SaveLocation(ctx context.Context, loc SensorLocation) error {
	ret := _mock.Called(ctx, loc)

	if len(ret) == 0 {
		panic("no return value specified for SaveLocation")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, SensorLocation) error); ok {
		r0 = returnFunc(ctx, loc)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDataJournal_SaveLocation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveLocation'
type MockDataJournal_SaveLocation_Call struct {
	*mock.Call
}

// SaveLocation is a helper method to define mock.On call
//   - ctx context.Context
//   - loc SensorLocation
func (_e *MockDataJournal_Expecter) SaveLocation(ctx any, loc any) *MockDataJournal_SaveLocation_Call {
	return &MockDataJournal_SaveLocation_Call{Call: _e.mock.On("SaveLocation", ctx, loc)}
}

func (_c *MockDataJournal_SaveLocation_Call) Run(run func(ctx context.Context, loc SensorLocation)) *MockDataJournal_SaveLocation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 SensorLocation
		if args[1] != nil {
			arg1 = args[1].(SensorLocation)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDataJournal_SaveLocation_Call) Return(err error) *MockDataJournal_SaveLocation_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDataJournal_SaveLocation_Call) RunAndReturn(run func(ctx context.Context, loc SensorLocation) error) *MockDataJournal_SaveLocation_Call {
	_c.Call.Return(run)
	return _c
}
