---
- name: sets pylon version
  set_fact:
    aristeus_pylon_version: 26.08.1
  when: aristeus_pylon_version is not defined

- name: sets the architecture
  set_fact:
    aristeus_pylon_arch: "{{ arch_map[ansible_facts.architecture] | default(ansible_facts.architecture) }}"
  vars:
    arch_map:
      aarch64: "aarch64"

- name: sets the target installer file
  set_fact:
    aristeus_pylon_setup_file: "pylon-{{aristeus_pylon_version}}_linux-{{aristeus_pylon_arch}}_setup.tar.gz"
    aristeus_pylon_source_file: "pylon-{{aristeus_pylon_version}}_linux-{{aristeus_pylon_arch}}.tar.gz"

- name: installs facts dependencies
  apt:
    name:
      - gstreamer1.0-tools
    state: present

- name: installs cutsom fact
  copy:
    src: aristeus_pylon_version.fact
    dest: /etc/ansible/facts.d/aristeus_pylon_version.fact
    owner: root
    group: root
    mode: '0755'
  register: custom_fact_installed

- name: reloads facts
  setup:
  when: custom_fact_installed.changed == True

- name: installs base programs
  import_tasks: install_pylon_base.yml

- name: installs gstreamer plugin
  import_tasks: install_pylon_gstreamer.yml
