// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package blemock

import (
	"github.com/go-ble/ble"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAdvertisement creates a new instance of MockAdvertisement. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAdvertisement(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAdvertisement {
	mock := &MockAdvertisement{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAdvertisement is an autogenerated mock type for the Advertisement type
type MockAdvertisement struct {
	mock.Mock
}

type MockAdvertisement_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAdvertisement) EXPECT() *MockAdvertisement_Expecter {
	return &MockAdvertisement_Expecter{mock: &_m.Mock}
}

// Addr provides a mock function for the type MockAdvertisement
func (_mock *MockAdvertisement) Addr() ble.Addr {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Addr")
	}

	var r0 ble.Addr
	if returnFunc, ok := ret.Get(0).(func() ble.Addr); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(ble.Addr)
		}
	}
	return r0
}

// MockAdvertisement_Addr_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Addr'
type MockAdvertisement_Addr_Call struct {
	*mock.Call
}

// Addr is a helper method to define mock.On call
func (_e *MockAdvertisement_Expecter) Addr() *MockAdvertisement_Addr_Call {
	return &MockAdvertisement_Addr_Call{Call: _e.mock.On("Addr")}
}

func (_c *MockAdvertisement_Addr_Call) Run(run func()) *MockAdvertisement_Addr_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAdvertisement_Addr_Call) Return(addr ble.Addr) *MockAdvertisement_Addr_Call {
	_c.Call.Return(addr)
	return _c
}

func (_c *MockAdvertisement_Addr_Call) RunAndReturn(run func() ble.Addr) *MockAdvertisement_Addr_Call {
	_c.Call.Return(run)
	return _c
}

// Connectable provides a mock function for the type MockAdvertisement
func (_mock *MockAdvertisement) Connectable() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Connectable")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockAdvertisement_Connectable_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Connectable'
type MockAdvertisement_Connectable_Call struct {
	*mock.Call
}

// Connectable is a helper method to define mock.On call
func (_e *MockAdvertisement_Expecter) Connectable() *MockAdvertisement_Connectable_Call {
	return &MockAdvertisement_Connectable_Call{Call: _e.mock.On("Connectable")}
}

func (_c *MockAdvertisement_Connectable_Call) Run(run func()) *MockAdvertisement_Connectable_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAdvertisement_Connectable_Call) Return(b bool) *MockAdvertisement_Connectable_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockAdvertisement_Connectable_Call) RunAndReturn(run func() bool) *MockAdvertisement_Connectable_Call {
	_c.Call.Return(run)
	return _c
}

// LocalName provides a mock function for the type MockAdvertisement
func (_mock *MockAdvertisement) LocalName() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for LocalName")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockAdvertisement_LocalName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LocalName'
type MockAdvertisement_LocalName_Call struct {
	*mock.Call
}

// LocalName is a helper method to define mock.On call
func (_e *MockAdvertisement_Expecter) LocalName() *MockAdvertisement_LocalName_Call {
	return &MockAdvertisement_LocalName_Call{Call: _e.mock.On("LocalName")}
}

func (_c *MockAdvertisement_LocalName_Call) Run(run func()) *MockAdvertisement_LocalName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAdvertisement_LocalName_Call) Return(s string) *MockAdvertisement_LocalName_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockAdvertisement_LocalName_Call) RunAndReturn(run func() string) *MockAdvertisement_LocalName_Call {
	_c.Call.Return(run)
	return _c
}

// ManufacturerData provides a mock function for the type MockAdvertisement
func (_mock *MockAdvertisement) ManufacturerData() []byte {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ManufacturerData")
	}

	var r0 []byte
	if returnFunc, ok := ret.Get(0).(func() []byte); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	return r0
}

// MockAdvertisement_ManufacturerData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ManufacturerData'
type MockAdvertisement_ManufacturerData_Call struct {
	*mock.Call
}

// ManufacturerData is a helper method to define mock.On call
func (_e *MockAdvertisement_Expecter) ManufacturerData() *MockAdvertisement_ManufacturerData_Call {
	return &MockAdvertisement_ManufacturerData_Call{Call: _e.mock.On("ManufacturerData")}
}

func (_c *MockAdvertisement_ManufacturerData_Call) Run(run func()) *MockAdvertisement_ManufacturerData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAdvertisement_ManufacturerData_Call) Return(bytes []byte) *MockAdvertisement_ManufacturerData_Call {
	_c.Call.Return(bytes)
	return _c
}

func (_c *MockAdvertisement_ManufacturerData_Call) RunAndReturn(run func() []byte) *MockAdvertisement_ManufacturerData_Call {
	_c.Call.Return(run)
	return _c
}

// OverflowService provides a mock function for the type MockAdvertisement
func (_mock *MockAdvertisement) OverflowService() []ble.UUID {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for OverflowService")
	}

	var r0 []ble.UUID
	if returnFunc, ok := ret.Get(0).(func() []ble.UUID); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]ble.UUID)
		}
	}
	return r0
}

// MockAdvertisement_OverflowService_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OverflowService'
type MockAdvertisement_OverflowService_Call struct {
	*mock.Call
}

// OverflowService is a helper method to define mock.On call
func (_e *MockAdvertisement_Expecter) OverflowService() *MockAdvertisement_OverflowService_Call {
	return &MockAdvertisement_OverflowService_Call{Call: _e.mock.On("OverflowService")}
}

func (_c *MockAdvertisement_OverflowService_Call) Run(run func()) *MockAdvertisement_OverflowService_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAdvertisement_OverflowService_Call) Return(uUIDs []ble.UUID) *MockAdvertisement_OverflowService_Call {
	_c.Call.Return(uUIDs)
	return _c
}

func (_c *MockAdvertisement_OverflowService_Call) RunAndReturn(run func() []ble.UUID) *MockAdvertisement_OverflowService_Call {
	_c.Call.Return(run)
	return _c
}

// RSSI provides a mock function for the type MockAdvertisement
func (_mock *MockAdvertisement) RSSI() int {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for RSSI")
	}

	var r0 int
	if returnFunc, ok := ret.Get(0).(func() int); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int)
	}
	return r0
}

// MockAdvertisement_RSSI_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RSSI'
type MockAdvertisement_RSSI_Call struct {
	*mock.Call
}

// RSSI is a helper method to define mock.On call
func (_e *MockAdvertisement_Expecter) RSSI() *MockAdvertisement_RSSI_Call {
	return &MockAdvertisement_RSSI_Call{Call: _e.mock.On("RSSI")}
}

func (_c *MockAdvertisement_RSSI_Call) Run(run func()) *MockAdvertisement_RSSI_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAdvertisement_RSSI_Call) Return(n int) *MockAdvertisement_RSSI_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *MockAdvertisement_RSSI_Call) RunAndReturn(run func() int) *MockAdvertisement_RSSI_Call {
	_c.Call.Return(run)
	return _c
}

// ServiceData provides a mock function for the type MockAdvertisement
func (_mock *MockAdvertisement) ServiceData() []ble.ServiceData {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ServiceData")
	}

	var r0 []ble.ServiceData
	if returnFunc, ok := ret.Get(0).(func() []ble.ServiceData); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]ble.ServiceData)
		}
	}
	return r0
}

// MockAdvertisement_ServiceData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ServiceData'
type MockAdvertisement_ServiceData_Call struct {
	*mock.Call
}

// ServiceData is a helper method to define mock.On call
func (_e *MockAdvertisement_Expecter) ServiceData() *MockAdvertisement_ServiceData_Call {
	return &MockAdvertisement_ServiceData_Call{Call: _e.mock.On("ServiceData")}
}

func (_c *MockAdvertisement_ServiceData_Call) Run(run func()) *MockAdvertisement_ServiceData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAdvertisement_ServiceData_Call) Return(serviceDatas []ble.ServiceData) *MockAdvertisement_ServiceData_Call {
	_c.Call.Return(serviceDatas)
	return _c
}

func (_c *MockAdvertisement_ServiceData_Call) RunAndReturn(run func() []ble.ServiceData) *MockAdvertisement_ServiceData_Call {
	_c.Call.Return(run)
	return _c
}

// Services provides a mock function for the type MockAdvertisement
func (_mock *MockAdvertisement) Services() []ble.UUID {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Services")
	}

	var r0 []ble.UUID
	if returnFunc, ok := ret.Get(0).(func() []ble.UUID); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]ble.UUID)
		}
	}
	return r0
}

// MockAdvertisement_Services_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Services'
type MockAdvertisement_Services_Call struct {
	*mock.Call
}

// Services is a helper method to define mock.On call
func (_e *MockAdvertisement_Expecter) Services() *MockAdvertisement_Services_Call {
	return &MockAdvertisement_Services_Call{Call: _e.mock.On("Services")}
}

func (_c *MockAdvertisement_Services_Call) Run(run func()) *MockAdvertisement_Services_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAdvertisement_Services_Call) Return(uUIDs []ble.UUID) *MockAdvertisement_Services_Call {
	_c.Call.Return(uUIDs)
	return _c
}

func (_c *MockAdvertisement_Services_Call) RunAndReturn(run func() []ble.UUID) *MockAdvertisement_Services_Call {
	_c.Call.Return(run)
	return _c
}

// SolicitedService provides a mock function for the type MockAdvertisement
func (_mock *MockAdvertisement) SolicitedService() []ble.UUID {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for SolicitedService")
	}

	var r0 []ble.UUID
	if returnFunc, ok := ret.Get(0).(func() []ble.UUID); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]ble.UUID)
		}
	}
	return r0
}

// MockAdvertisement_SolicitedService_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SolicitedService'
type MockAdvertisement_SolicitedService_Call struct {
	*mock.Call
}

// SolicitedService is a helper method to define mock.On call
func (_e *MockAdvertisement_Expecter) SolicitedService() *MockAdvertisement_SolicitedService_Call {
	return &MockAdvertisement_SolicitedService_Call{Call: _e.mock.On("SolicitedService")}
}

func (_c *MockAdvertisement_SolicitedService_Call) Run(run func()) *MockAdvertisement_SolicitedService_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAdvertisement_SolicitedService_Call) Return(uUIDs []ble.UUID) *MockAdvertisement_SolicitedService_Call {
	_c.Call.Return(uUIDs)
	return _c
}

func (_c *MockAdvertisement_SolicitedService_Call) RunAndReturn(run func() []ble.UUID) *MockAdvertisement_SolicitedService_Call {
	_c.Call.Return(run)
	return _c
}

// TxPowerLevel provides a mock function for the type MockAdvertisement
func (_mock *MockAdvertisement) TxPowerLevel() int {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for TxPowerLevel")
	}

	var r0 int
	if returnFunc, ok := ret.Get(0).(func() int); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int)
	}
	return r0
}

// MockAdvertisement_TxPowerLevel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TxPowerLevel'
type MockAdvertisement_TxPowerLevel_Call struct {
	*mock.Call
}

// TxPowerLevel is a helper method to define mock.On call
func (_e *MockAdvertisement_Expecter) TxPowerLevel() *MockAdvertisement_TxPowerLevel_Call {
	return &MockAdvertisement_TxPowerLevel_Call{Call: _e.mock.On("TxPowerLevel")}
}

func (_c *MockAdvertisement_TxPowerLevel_Call) Run(run func()) *MockAdvertisement_TxPowerLevel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAdvertisement_TxPowerLevel_Call) Return(n int) *MockAdvertisement_TxPowerLevel_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *MockAdvertisement_TxPowerLevel_Call) RunAndReturn(run func() int) *MockAdvertisement_TxPowerLevel_Call {
	_c.Call.Return(run)
	return _c
}
