// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package main

import (
	"context"
	"time"

	"github.com/go-ble/ble"
	mock "github.com/stretchr/testify/mock"
)

// NewMockBLEDevice creates a new instance of MockBLEDevice. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBLEDevice(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBLEDevice {
	mock := &MockBLEDevice{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBLEDevice is an autogenerated mock type for the BLEDevice type
type MockBLEDevice struct {
	mock.Mock
}

type MockBLEDevice_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBLEDevice) EXPECT() *MockBLEDevice_Expecter {
	return &MockBLEDevice_Expecter{mock: &_m.Mock}
}

// Dial provides a mock function for the type MockBLEDevice
func (_mock *MockBLEDevice) Dial(context1 context.Context, addr ble.Addr) (ble.Client, error) {
	ret := _mock.Called(context1, addr)

	if len(ret) == 0 {
		panic("no return value specified for Dial")
	}

	var r0 ble.Client
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ble.Addr) (ble.Client, error)); ok {
		return returnFunc(context1, addr)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ble.Addr) ble.Client); ok {
		r0 = returnFunc(context1, addr)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(ble.Client)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ble.Addr) error); ok {
		r1 = returnFunc(context1, addr)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBLEDevice_Dial_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Dial'
type MockBLEDevice_Dial_Call struct {
	*mock.Call
}

// Dial is a helper method to define mock.On call
//   - context1 context.Context
//   - addr ble.Addr
func (_e *MockBLEDevice_Expecter) Dial(context1 any, addr any) *MockBLEDevice_Dial_Call {
	return &MockBLEDevice_Dial_Call{Call: _e.mock.On("Dial", context1, addr)}
}

func (_c *MockBLEDevice_Dial_Call) Run(run func(context1 context.Context, addr ble.Addr)) *MockBLEDevice_Dial_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ble.Addr
		if args[1] != nil {
			arg1 = args[1].(ble.Addr)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBLEDevice_Dial_Call) Return(client ble.Client, err error) *MockBLEDevice_Dial_Call {
	_c.Call.Return(client, err)
	return _c
}

func (_c *MockBLEDevice_Dial_Call) RunAndReturn(run func(context1 context.Context, addr ble.Addr) (ble.Client, error)) *MockBLEDevice_Dial_Call {
	_c.Call.Return(run)
	return _c
}

// Scan provides a mock function for the type MockBLEDevice
func (_mock *MockBLEDevice) Scan(ctx context.Context, allowDuplicates bool, handler ble.AdvHandler) error {
	ret := _mock.Called(ctx, allowDuplicates, handler)

	if len(ret) == 0 {
		panic("no return value specified for Scan")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, bool, ble.AdvHandler) error); ok {
		r0 = returnFunc(ctx, allowDuplicates, handler)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBLEDevice_Scan_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Scan'
type MockBLEDevice_Scan_Call struct {
	*mock.Call
}

// Scan is a helper method to define mock.On call
//   - ctx context.Context
//   - allowDuplicates bool
//   - handler ble.AdvHandler
func (_e *MockBLEDevice_Expecter) Scan(ctx any, allowDuplicates any, handler any) *MockBLEDevice_Scan_Call {
	return &MockBLEDevice_Scan_Call{Call: _e.mock.On("Scan", ctx, allowDuplicates, handler)}
}

func (_c *MockBLEDevice_Scan_Call) Run(run func(ctx context.Context, allowDuplicates bool, handler ble.AdvHandler)) *MockBLEDevice_Scan_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 bool
		if args[1] != nil {
			arg1 = args[1].(bool)
		}
		var arg2 ble.AdvHandler
		if args[2] != nil {
			arg2 = args[2].(ble.AdvHandler)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockBLEDevice_Scan_Call) Return(err error) *MockBLEDevice_Scan_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBLEDevice_Scan_Call) RunAndReturn(run func(ctx context.Context, allowDuplicates bool, handler ble.AdvHandler) error) *MockBLEDevice_Scan_Call {
	_c.Call.Return(run)
	return _c
}

// newMockbleDevice creates a new instance of mockbleDevice. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockbleDevice(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockbleDevice {
	mock := &mockbleDevice{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockbleDevice is an autogenerated mock type for the bleDevice type
type mockbleDevice struct {
	mock.Mock
}

type mockbleDevice_Expecter struct {
	mock *mock.Mock
}

func (_m *mockbleDevice) EXPECT() *mockbleDevice_Expecter {
	return &mockbleDevice_Expecter{mock: &_m.Mock}
}

// Dial provides a mock function for the type mockbleDevice
func (_mock *mockbleDevice) Dial(context1 context.Context, addr ble.Addr) (ble.Client, error) {
	ret := _mock.Called(context1, addr)

	if len(ret) == 0 {
		panic("no return value specified for Dial")
	}

	var r0 ble.Client
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ble.Addr) (ble.Client, error)); ok {
		return returnFunc(context1, addr)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ble.Addr) ble.Client); ok {
		r0 = returnFunc(context1, addr)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(ble.Client)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ble.Addr) error); ok {
		r1 = returnFunc(context1, addr)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockbleDevice_Dial_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Dial'
type mockbleDevice_Dial_Call struct {
	*mock.Call
}

// Dial is a helper method to define mock.On call
//   - context1 context.Context
//   - addr ble.Addr
func (_e *mockbleDevice_Expecter) Dial(context1 any, addr any) *mockbleDevice_Dial_Call {
	return &mockbleDevice_Dial_Call{Call: _e.mock.On("Dial", context1, addr)}
}

func (_c *mockbleDevice_Dial_Call) Run(run func(context1 context.Context, addr ble.Addr)) *mockbleDevice_Dial_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ble.Addr
		if args[1] != nil {
			arg1 = args[1].(ble.Addr)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockbleDevice_Dial_Call) Return(client ble.Client, err error) *mockbleDevice_Dial_Call {
	_c.Call.Return(client, err)
	return _c
}

func (_c *mockbleDevice_Dial_Call) RunAndReturn(run func(context1 context.Context, addr ble.Addr) (ble.Client, error)) *mockbleDevice_Dial_Call {
	_c.Call.Return(run)
	return _c
}

// Scan provides a mock function for the type mockbleDevice
func (_mock *mockbleDevice) Scan(ctx context.Context, allowDuplicates bool, handler ble.AdvHandler) error {
	ret := _mock.Called(ctx, allowDuplicates, handler)

	if len(ret) == 0 {
		panic("no return value specified for Scan")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, bool, ble.AdvHandler) error); ok {
		r0 = returnFunc(ctx, allowDuplicates, handler)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockbleDevice_Scan_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Scan'
type mockbleDevice_Scan_Call struct {
	*mock.Call
}

// Scan is a helper method to define mock.On call
//   - ctx context.Context
//   - allowDuplicates bool
//   - handler ble.AdvHandler
func (_e *mockbleDevice_Expecter) Scan(ctx any, allowDuplicates any, handler any) *mockbleDevice_Scan_Call {
	return &mockbleDevice_Scan_Call{Call: _e.mock.On("Scan", ctx, allowDuplicates, handler)}
}

func (_c *mockbleDevice_Scan_Call) Run(run func(ctx context.Context, allowDuplicates bool, handler ble.AdvHandler)) *mockbleDevice_Scan_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 bool
		if args[1] != nil {
			arg1 = args[1].(bool)
		}
		var arg2 ble.AdvHandler
		if args[2] != nil {
			arg2 = args[2].(ble.AdvHandler)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockbleDevice_Scan_Call) Return(err error) *mockbleDevice_Scan_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockbleDevice_Scan_Call) RunAndReturn(run func(ctx context.Context, allowDuplicates bool, handler ble.AdvHandler) error) *mockbleDevice_Scan_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockDataJournal creates a new instance of MockDataJournal. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDataJournal(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDataJournal {
	mock := &MockDataJournal{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDataJournal is an autogenerated mock type for the DataJournal type
type MockDataJournal struct {
	mock.Mock
}

type MockDataJournal_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDataJournal) EXPECT() *MockDataJournal_Expecter {
	return &MockDataJournal_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type MockDataJournal
func (_mock *MockDataJournal) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDataJournal_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockDataJournal_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockDataJournal_Expecter) Close() *MockDataJournal_Close_Call {
	return &MockDataJournal_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockDataJournal_Close_Call) Run(run func()) *MockDataJournal_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDataJournal_Close_Call) Return(err error) *MockDataJournal_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDataJournal_Close_Call) RunAndReturn(run func() error) *MockDataJournal_Close_Call {
	_c.Call.Return(run)
	return _c
}

// GetActiveAssignments provides a mock function for the type MockDataJournal
func (_mock *MockDataJournal) GetActiveAssignments(ctx context.Context) ([]SensorAssignement, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetActiveAssignments")
	}

	var r0 []SensorAssignement
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]SensorAssignement, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []SensorAssignement); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]SensorAssignement)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDataJournal_GetActiveAssignments_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetActiveAssignments'
type MockDataJournal_GetActiveAssignments_Call struct {
	*mock.Call
}

// GetActiveAssignments is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockDataJournal_Expecter) GetActiveAssignments(ctx any) *MockDataJournal_GetActiveAssignments_Call {
	return &MockDataJournal_GetActiveAssignments_Call{Call: _e.mock.On("GetActiveAssignments", ctx)}
}

func (_c *MockDataJournal_GetActiveAssignments_Call) Run(run func(ctx context.Context)) *MockDataJournal_GetActiveAssignments_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDataJournal_GetActiveAssignments_Call) Return(sensorAssignements []SensorAssignement, err error) *MockDataJournal_GetActiveAssignments_Call {
	_c.Call.Return(sensorAssignements, err)
	return _c
}

func (_c *MockDataJournal_GetActiveAssignments_Call) RunAndReturn(run func(ctx context.Context) ([]SensorAssignement, error)) *MockDataJournal_GetActiveAssignments_Call {
	_c.Call.Return(run)
	return _c
}

// GetEnvironmentalHistory provides a mock function for the type MockDataJournal
func (_mock *MockDataJournal) GetEnvironmentalHistory(ctx context.Context, locationID string, start time.Time, end time.Time) ([]EnvironmentalReading, error) {
	ret := _mock.Called(ctx, locationID, start, end)

	if len(ret) == 0 {
		panic("no return value specified for GetEnvironmentalHistory")
	}

	var r0 []EnvironmentalReading
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Time, time.Time) ([]EnvironmentalReading, error)); ok {
		return returnFunc(ctx, locationID, start, end)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Time, time.Time) []EnvironmentalReading); ok {
		r0 = returnFunc(ctx, locationID, start, end)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]EnvironmentalReading)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, time.Time, time.Time) error); ok {
		r1 = returnFunc(ctx, locationID, start, end)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDataJournal_GetEnvironmentalHistory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEnvironmentalHistory'
type MockDataJournal_GetEnvironmentalHistory_Call struct {
	*mock.Call
}

// GetEnvironmentalHistory is a helper method to define mock.On call
//   - ctx context.Context
//   - locationID string
//   - start time.Time
//   - end time.Time
func (_e *MockDataJournal_Expecter) GetEnvironmentalHistory(ctx any, locationID any, start any, end any) *MockDataJournal_GetEnvironmentalHistory_Call {
	return &MockDataJournal_GetEnvironmentalHistory_Call{Call: _e.mock.On("GetEnvironmentalHistory", ctx, locationID, start, end)}
}

func (_c *MockDataJournal_GetEnvironmentalHistory_Call) Run(run func(ctx context.Context, locationID string, start time.Time, end time.Time)) *MockDataJournal_GetEnvironmentalHistory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		var arg3 time.Time
		if args[3] != nil {
			arg3 = args[3].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockDataJournal_GetEnvironmentalHistory_Call) Return(environmentalReadings []EnvironmentalReading, err error) *MockDataJournal_GetEnvironmentalHistory_Call {
	_c.Call.Return(environmentalReadings, err)
	return _c
}

func (_c *MockDataJournal_GetEnvironmentalHistory_Call) RunAndReturn(run func(ctx context.Context, locationID string, start time.Time, end time.Time) ([]EnvironmentalReading, error)) *MockDataJournal_GetEnvironmentalHistory_Call {
	_c.Call.Return(run)
	return _c
}

// GetLocationAssignements provides a mock function for the type MockDataJournal
func (_mock *MockDataJournal) GetLocationAssignements(ctx context.Context, locationID string) ([]SensorAssignement, error) {
	ret := _mock.Called(ctx, locationID)

	if len(ret) == 0 {
		panic("no return value specified for GetLocationAssignements")
	}

	var r0 []SensorAssignement
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]SensorAssignement, error)); ok {
		return returnFunc(ctx, locationID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []SensorAssignement); ok {
		r0 = returnFunc(ctx, locationID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]SensorAssignement)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, locationID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDataJournal_GetLocationAssignements_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLocationAssignements'
type MockDataJournal_GetLocationAssignements_Call struct {
	*mock.Call
}

// GetLocationAssignements is a helper method to define mock.On call
//   - ctx context.Context
//   - locationID string
func (_e *MockDataJournal_Expecter) GetLocationAssignements(ctx any, locationID any) *MockDataJournal_GetLocationAssignements_Call {
	return &MockDataJournal_GetLocationAssignements_Call{Call: _e.mock.On("GetLocationAssignements", ctx, locationID)}
}

func (_c *MockDataJournal_GetLocationAssignements_Call) Run(run func(ctx context.Context, locationID string)) *MockDataJournal_GetLocationAssignements_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDataJournal_GetLocationAssignements_Call) Return(sensorAssignements []SensorAssignement, err error) *MockDataJournal_GetLocationAssignements_Call {
	_c.Call.Return(sensorAssignements, err)
	return _c
}

func (_c *MockDataJournal_GetLocationAssignements_Call) RunAndReturn(run func(ctx context.Context, locationID string) ([]SensorAssignement, error)) *MockDataJournal_GetLocationAssignements_Call {
	_c.Call.Return(run)
	return _c
}

// GetSensorAssignements provides a mock function for the type MockDataJournal
func (_mock *MockDataJournal) GetSensorAssignements(ctx context.Context, sensorID string) ([]SensorAssignement, error) {
	ret := _mock.Called(ctx, sensorID)

	if len(ret) == 0 {
		panic("no return value specified for GetSensorAssignements")
	}

	var r0 []SensorAssignement
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]SensorAssignement, error)); ok {
		return returnFunc(ctx, sensorID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []SensorAssignement); ok {
		r0 = returnFunc(ctx, sensorID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]SensorAssignement)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, sensorID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDataJournal_GetSensorAssignements_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSensorAssignements'
type MockDataJournal_GetSensorAssignements_Call struct {
	*mock.Call
}

// GetSensorAssignements is a helper method to define mock.On call
//   - ctx context.Context
//   - sensorID string
func (_e *MockDataJournal_Expecter) GetSensorAssignements(ctx any, sensorID any) *MockDataJournal_GetSensorAssignements_Call {
	return &MockDataJournal_GetSensorAssignements_Call{Call: _e.mock.On("GetSensorAssignements", ctx, sensorID)}
}

func (_c *MockDataJournal_GetSensorAssignements_Call) Run(run func(ctx context.Context, sensorID string)) *MockDataJournal_GetSensorAssignements_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDataJournal_GetSensorAssignements_Call) Return(sensorAssignements []SensorAssignement, err error) *MockDataJournal_GetSensorAssignements_Call {
	_c.Call.Return(sensorAssignements, err)
	return _c
}

func (_c *MockDataJournal_GetSensorAssignements_Call) RunAndReturn(run func(ctx context.Context, sensorID string) ([]SensorAssignement, error)) *MockDataJournal_GetSensorAssignements_Call {
	_c.Call.Return(run)
	return _c
}

// GetSensorLocations provides a mock function for the type MockDataJournal
func (_mock *MockDataJournal) GetSensorLocations(ctx context.Context) ([]SensorLocation, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetSensorLocations")
	}

	var r0 []SensorLocation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]SensorLocation, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []SensorLocation); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]SensorLocation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDataJournal_GetSensorLocations_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSensorLocations'
type MockDataJournal_GetSensorLocations_Call struct {
	*mock.Call
}

// GetSensorLocations is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockDataJournal_Expecter) GetSensorLocations(ctx any) *MockDataJournal_GetSensorLocations_Call {
	return &MockDataJournal_GetSensorLocations_Call{Call: _e.mock.On("GetSensorLocations", ctx)}
}

func (_c *MockDataJournal_GetSensorLocations_Call) Run(run func(ctx context.Context)) *MockDataJournal_GetSensorLocations_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDataJournal_GetSensorLocations_Call) Return(sensorLocations []SensorLocation, err error) *MockDataJournal_GetSensorLocations_Call {
	_c.Call.Return(sensorLocations, err)
	return _c
}

func (_c *MockDataJournal_GetSensorLocations_Call) RunAndReturn(run func(ctx context.Context) ([]SensorLocation, error)) *MockDataJournal_GetSensorLocations_Call {
	_c.Call.Return(run)
	return _c
}

// SaveEnvironmentalReadings provides a mock function for the type MockDataJournal
func (_mock *MockDataJournal) SaveEnvironmentalReadings(ctx context.Context, readings []EnvironmentalReading) error {
	ret := _mock.Called(ctx, readings)

	if len(ret) == 0 {
		panic("no return value specified for SaveEnvironmentalReadings")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []EnvironmentalReading) error); ok {
		r0 = returnFunc(ctx, readings)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDataJournal_SaveEnvironmentalReadings_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveEnvironmentalReadings'
type MockDataJournal_SaveEnvironmentalReadings_Call struct {
	*mock.Call
}

// SaveEnvironmentalReadings is a helper method to define mock.On call
//   - ctx context.Context
//   - readings []EnvironmentalReading
func (_e *MockDataJournal_Expecter) SaveEnvironmentalReadings(ctx any, readings any) *MockDataJournal_SaveEnvironmentalReadings_Call {
	return &MockDataJournal_SaveEnvironmentalReadings_Call{Call: _e.mock.On("SaveEnvironmentalReadings", ctx, readings)}
}

func (_c *MockDataJournal_SaveEnvironmentalReadings_Call) Run(run func(ctx context.Context, readings []EnvironmentalReading)) *MockDataJournal_SaveEnvironmentalReadings_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []EnvironmentalReading
		if args[1] != nil {
			arg1 = args[1].([]EnvironmentalReading)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDataJournal_SaveEnvironmentalReadings_Call) Return(err error) *MockDataJournal_SaveEnvironmentalReadings_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDataJournal_SaveEnvironmentalReadings_Call) RunAndReturn(run func(ctx context.Context, readings []EnvironmentalReading) error) *MockDataJournal_SaveEnvironmentalReadings_Call {
	_c.Call.Return(run)
	return _c
}

// SaveLocation provides a mock function for the type MockDataJournal
func (_mock *MockDataJournal) SaveLocation(ctx context.Context, loc SensorLocation) error {
	ret := _mock.Called(ctx, loc)

	if len(ret) == 0 {
		panic("no return value specified for SaveLocation")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, SensorLocation) error); ok {
		r0 = returnFunc(ctx, loc)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDataJournal_SaveLocation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveLocation'
type MockDataJournal_SaveLocation_Call struct {
	*mock.Call
}

// SaveLocation is a helper method to define mock.On call
//   - ctx context.Context
//   - loc SensorLocation
func (_e *MockDataJournal_Expecter) SaveLocation(ctx any, loc any) *MockDataJournal_SaveLocation_Call {
	return &MockDataJournal_SaveLocation_Call{Call: _e.mock.On("SaveLocation", ctx, loc)}
}

func (_c *MockDataJournal_SaveLocation_Call) Run(run func(ctx context.Context, loc SensorLocation)) *MockDataJournal_SaveLocation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 SensorLocation
		if args[1] != nil {
			arg1 = args[1].(SensorLocation)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDataJournal_SaveLocation_Call) Return(err error) *MockDataJournal_SaveLocation_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDataJournal_SaveLocation_Call) RunAndReturn(run func(ctx context.Context, loc SensorLocation) error) *MockDataJournal_SaveLocation_Call {
	_c.Call.Return(run)
	return _c
}
