// Code generated by "stringer -type=RegisterAddress"; DO NOT EDIT.

package emc2101

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[InternalTemperatureRegister-0]
	_ = x[ExternalTemperatureHighBRegister-1]
	_ = x[StatusRegister-2]
	_ = x[ConfigurationRegister-3]
	_ = x[ConversionRateRegister-4]
	_ = x[InternalTemperatureLimitRegister-5]
	_ = x[ExternalTemperatureLimitHighBRegister-6]
	_ = x[ExternalTemperatureLimitLowBRegister-7]
	_ = x[ExternalTemperatureForceRegister-8]
	_ = x[OneShotRegister-9]
	_ = x[ExternalTemperatureLowBRegister-16]
	_ = x[ExternalDiodeLimitHighBRegister-19]
	_ = x[ExternalDiodeLimitLowBRegister-20]
	_ = x[AlertMaskRegister-22]
	_ = x[ExternalDiodeIdealityFactorRegister-23]
	_ = x[BetaCompensationFactorRegister-24]
	_ = x[TCritTempLimitRegister-25]
	_ = x[TCritHisteresysRegister-33]
	_ = x[TachReadingLowBRegister-70]
	_ = x[TachReadingHighBRegister-71]
	_ = x[TachLimitLowBRegister-72]
	_ = x[TachLimitHighBRegister-73]
	_ = x[FanConfigurationRegister-74]
	_ = x[FanSpinUpRegister-75]
	_ = x[FanSettingRegister-76]
	_ = x[PWMFrequencyRegister-77]
	_ = x[PWMFrequencyDivideRegister-78]
	_ = x[LUTHysteresisRegister-79]
	_ = x[LUTSetTemperature1Register-80]
	_ = x[LUTSetPWM1Register-81]
	_ = x[LUTSetTemperature2Register-82]
	_ = x[LUTSetPWM2Register-83]
	_ = x[LUTSetTemperature3Register-84]
	_ = x[LUTSetPWM3Register-85]
	_ = x[LUTSetTemperature4Register-86]
	_ = x[LUTSetPWM4Register-87]
	_ = x[LUTSetTemperature5Register-88]
	_ = x[LUTSetPWM5Register-89]
	_ = x[LUTSetTemperature6Register-90]
	_ = x[LUTSetPWM6Register-91]
	_ = x[LUTSetTemperature7Register-92]
	_ = x[LUTSetPWM7Register-93]
	_ = x[LUTSetTemperature8Register-94]
	_ = x[LUTSetPWM8Register-95]
	_ = x[AveragingFilterRegister-191]
	_ = x[ProductIDRegister-253]
	_ = x[ManufacturerIDRegister-254]
	_ = x[RevisionRegister-255]
}

const (
	_RegisterAddress_name_0 = "InternalTemperatureRegisterExternalTemperatureHighBRegisterStatusRegisterConfigurationRegisterConversionRateRegisterInternalTemperatureLimitRegisterExternalTemperatureLimitHighBRegisterExternalTemperatureLimitLowBRegisterExternalTemperatureForceRegisterOneShotRegister"
	_RegisterAddress_name_1 = "ExternalTemperatureLowBRegister"
	_RegisterAddress_name_2 = "ExternalDiodeLimitHighBRegisterExternalDiodeLimitLowBRegister"
	_RegisterAddress_name_3 = "AlertMaskRegisterExternalDiodeIdealityFactorRegisterBetaCompensationFactorRegisterTCritTempLimitRegister"
	_RegisterAddress_name_4 = "TCritHisteresysRegister"
	_RegisterAddress_name_5 = "TachReadingLowBRegisterTachReadingHighBRegisterTachLimitLowBRegisterTachLimitHighBRegisterFanConfigurationRegisterFanSpinUpRegisterFanSettingRegisterPWMFrequencyRegisterPWMFrequencyDivideRegisterLUTHysteresisRegisterLUTSetTemperature1RegisterLUTSetPWM1RegisterLUTSetTemperature2RegisterLUTSetPWM2RegisterLUTSetTemperature3RegisterLUTSetPWM3RegisterLUTSetTemperature4RegisterLUTSetPWM4RegisterLUTSetTemperature5RegisterLUTSetPWM5RegisterLUTSetTemperature6RegisterLUTSetPWM6RegisterLUTSetTemperature7RegisterLUTSetPWM7RegisterLUTSetTemperature8RegisterLUTSetPWM8Register"
	_RegisterAddress_name_6 = "AveragingFilterRegister"
	_RegisterAddress_name_7 = "ProductIDRegisterManufacturerIDRegisterRevisionRegister"
)

var (
	_RegisterAddress_index_0 = [...]uint16{0, 27, 59, 73, 94, 116, 148, 185, 221, 253, 268}
	_RegisterAddress_index_2 = [...]uint8{0, 31, 61}
	_RegisterAddress_index_3 = [...]uint8{0, 17, 52, 82, 104}
	_RegisterAddress_index_5 = [...]uint16{0, 23, 47, 68, 90, 114, 131, 149, 169, 195, 216, 242, 260, 286, 304, 330, 348, 374, 392, 418, 436, 462, 480, 506, 524, 550, 568}
	_RegisterAddress_index_7 = [...]uint8{0, 17, 39, 55}
)

func (i RegisterAddress) String() string {
	switch {
	case i <= 9:
		return _RegisterAddress_name_0[_RegisterAddress_index_0[i]:_RegisterAddress_index_0[i+1]]
	case i == 16:
		return _RegisterAddress_name_1
	case 19 <= i && i <= 20:
		i -= 19
		return _RegisterAddress_name_2[_RegisterAddress_index_2[i]:_RegisterAddress_index_2[i+1]]
	case 22 <= i && i <= 25:
		i -= 22
		return _RegisterAddress_name_3[_RegisterAddress_index_3[i]:_RegisterAddress_index_3[i+1]]
	case i == 33:
		return _RegisterAddress_name_4
	case 70 <= i && i <= 95:
		i -= 70
		return _RegisterAddress_name_5[_RegisterAddress_index_5[i]:_RegisterAddress_index_5[i+1]]
	case i == 191:
		return _RegisterAddress_name_6
	case 253 <= i && i <= 255:
		i -= 253
		return _RegisterAddress_name_7[_RegisterAddress_index_7[i]:_RegisterAddress_index_7[i+1]]
	default:
		return "RegisterAddress(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
