packages:
  github.com/atuleu/aristeus/go/pkg/collector:
    interfaces:
      DataJournal:
      BLEDevice:
      BLEScanner:
      Clock:
      CronScheduler:
  github.com/go-ble/ble:
    config:
      dir: "internal/blemock"
      filename: "mocks.go"
      pkgname: "blemock"
    interfaces:
      Advertisement:
