packages:
  github.com/atuleu/aristeus/go/pkg/collector:
    interfaces:
      DataJournal:
      BLEDevice:
      BLEScanner:
      Clock:
      CronScheduler:
      environmentalOperator:
  github.com/go-ble/ble:
    config:
      dir: "internal/blemock"
      filename: "mocks.go"
      pkgname: "blemock"
    interfaces:
      Advertisement:
  github.com/atuleu/aristeus/go/pkg/sse:
    interfaces:
      SSEWriter:
  net/http:
    config:
      dir: "pkg/sse"
      pkgname: "sse"
      filename: "mock_http_response_writer_test.go"
    interfaces:
      ResponseWriter:
